// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATZ90QhPSQmPGW5553YzP-6US_loRYF48',
    appId: '1:378085307622:web:bdc658827016d609d83727',
    messagingSenderId: '378085307622',
    projectId: 'event-panning-app',
    authDomain: 'event-panning-app.firebaseapp.com',
    storageBucket: 'event-panning-app.firebasestorage.app',
    measurementId: 'G-RC5R2VBC5L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvAfwSTmpcGvonadFsycuuKdNAx3AtmCQ',
    appId: '1:378085307622:android:2cae0a072dce4093d83727',
    messagingSenderId: '378085307622',
    projectId: 'event-panning-app',
    storageBucket: 'event-panning-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWdDxAMrDXyDkBDqusnDA5tKHa4xIM2ek',
    appId: '1:378085307622:ios:e943cdd1ba80d1b9d83727',
    messagingSenderId: '378085307622',
    projectId: 'event-panning-app',
    storageBucket: 'event-panning-app.firebasestorage.app',
    iosBundleId: 'com.example.eventPlanningApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAWdDxAMrDXyDkBDqusnDA5tKHa4xIM2ek',
    appId: '1:378085307622:ios:e943cdd1ba80d1b9d83727',
    messagingSenderId: '378085307622',
    projectId: 'event-panning-app',
    storageBucket: 'event-panning-app.firebasestorage.app',
    iosBundleId: 'com.example.eventPlanningApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyATZ90QhPSQmPGW5553YzP-6US_loRYF48',
    appId: '1:378085307622:web:be9df88b9adc64b6d83727',
    messagingSenderId: '378085307622',
    projectId: 'event-panning-app',
    authDomain: 'event-panning-app.firebaseapp.com',
    storageBucket: 'event-panning-app.firebasestorage.app',
    measurementId: 'G-FRWZ8B5H7S',
  );
}
